### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by KyleTryon** [autifyhq/autify-circleci-orb-mobile#2]
Hello Autify team,

I am from the @CircleCI Community and Partner Engineering team, here to help with a review for CircleCI orb partnership. I have a few items listed below for changes:

1. Rename the example to show a use-case
  a. Each provided usage example has a name which should reflect what the use-case is of that example
  b. Example: `mobile-e2e-test`
2. Move documentation out of the description
  a. The description of the orb is used for SEO purposes. Documentation should be listed within the orb itself via parameters.
  b. Consider making your homepage link, a link to further documentation for this integration hosted on your website.
3. Add a parameter for API tokens
  a. As per [best practices](https://circleci.com/docs/2.0/orb-author-faq/#secure-api-tokens), API tokens should be parameterized, so the user may if needed, provide an alternate environment variable.
  b. Having the token parameterized, also gives you as the developer a chance to document this in the parameter description.
  c. Here is an example:
    1. YAML: https://github.com/CircleCI-Public/github-cli-orb/blob/66c645413222b055ba90c31f2b73bbb6284dc6a0/src/commands/setup.yml#L11
    2. BASH: https://github.com/CircleCI-Public/github-cli-orb/blob/66c645413222b055ba90c31f2b73bbb6284dc6a0/src/scripts/configure.sh#L3
 4. Last just a request/question. What type of information is returned from these tests? Could the data be returned to CircleCI in JUNIT? If yes, we can display information about these results visually in our UI.
 
 Please let us know if you have any questions.

**Comment by riywo** [comment]
Addressed by #4
